### ISSUE TITLE
Could you please add an option to show/hide menubar?

### ISSUE THREAD

**Issue by mrpeabody** [andirsun/Slacky#11]
Most electron-based apps (VSCode, Slack, etc) allow hiding menubar (and optionally, show/hide with Alt/Option key). This wrapper is amazing, working really well -- apart from supporting a system tray icon it's basically a full nice slack experience on Fedora Asahi. Thank you for your work!

**Comment by andirsun** [comment]
@mrpeabody please check the releases page, I just pushed a new update

**Comment by mrpeabody** [comment]
works like a charm, thank you!

**Comment by andirsun** [comment]
Great! Thanks for testing the app.

Let me know if there is anything else you need.

Em sáb., 27 de abr. de 2024 às 19:53, Pavel K ***@***.***(mailto:Em sáb., 27 de abr. de 2024 às 19:53, Pavel K <<a href=)> escreveu:

**Comment by andirsun** [comment]
Great!
Thanks for testing the app.
Let me know if there is anything else I can do for you
