### ISSUE TITLE
AppImage crashes on startup on Ubuntu 24.10 (aarch64), missing libz.so.

### ISSUE THREAD

**Issue by orende** [andirsun/Slacky#19]
I just tried running the 0.0.4 AppImage on Ubuntu 24.10 on an ARM laptop, but got the following error:

> $ ./Slacky-0.0.4-arm64.AppImage 
> ./Slacky-0.0.4-arm64.AppImage: error while loading shared libraries: libz.so: cannot open shared object file: No such file or directory

Not much to go on, but let me know if you need any additional debugging info.

**Comment by jmastr** [comment]
@orende have you tried to `sudo apt-get install zlib1g-dev`? according to https://packages.ubuntu.com/search?suite=oracular&section=all&arch=any&keywords=libz.so&searchon=contents this provides `libz.so` for ubuntu 24.10 arm64...

**Comment by orende** [comment]
I just tried installing zlib1g-dev, but it led to another crash with this error message:

> $ ./Slacky-0.0.4-arm64.AppImage 
[12442:1111/105642.053225:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Slackyt5lsAa/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)

**Comment by jmastr** [comment]
@orende according to: https://askubuntu.com/a/1512288

You could run your appimage with the `--no-sandbox` option or you can try `--disable-setuid-sandbox`, i.e. `./Slacky-0.0.4-arm64.AppImage --no-sandbox` or `./Slacky-0.0.4-arm64.AppImage --disable-setuid-sandbox`.

**Comment by orende** [comment]
Ah, didn't realize that was an AppImage-specific error. Running with `--no-sandbox` worked, closing issue.
