### ISSUE TITLE
 Huddle fullscreen opens default browser instead of electron window (

### ISSUE THREAD

**Issue by daemonp** [andirsun/Slacky#8]
Thank you for creating this awesome project! Having Slack outside of a browser tab on arm64 is fantastic! :bow: 

As the title suggests, I'm encountering an issue where attempting to open a Huddle in fullscreen mode triggers the default browser instead of utilizing an electron child window.

#### Expected behaviour:

Clicking the fullscreen button on a Huddle opens it within the same electron window, filling the available space.

#### Actual behaviour:

Clicking the fullscreen button opens a blank page in the default browser.

#### Additional information:

I'm unfamiliar with the project codebase yet, but I'll try researching potential solutions and contribute a pull request.

**Comment by andirsun** [comment]
Thanks for the report @daemonp! 
I will fix the error this week and publish an update. I will keep you posted

**Comment by andirsun** [comment]
@daemonp Could you please give me exact steps to reproduce it ?

**Comment by andirsun** [comment]
Closing this for now as is not a priority and there was no reponse from user. I can re-open it in the future if needed.
